import HomeScreen from './home/HomeScreen'
import Splash from './splash/Splash'
import Login from './auth/Login'
import Signup from './auth/Signup'
import OTP from './auth/OTP'
import Onboarding from './auth/Onboarding'
import NewPassword from './auth/NewPassword'
import ForgetPassword from './auth/ForgetPassword'
import DocumentScreen from './document/DocumentScreen'
export { HomeScreen, Splash, Login, Signup, OTP, Onboarding, NewPassword, ForgetPassword, DocumentScreen }
